<Project>
  <ItemGroup>
    <LlmTckServiceContent Include="$(MSBuildThisFileDirectory)..\tools\llm-tck-service\**\*" />
    <None
      Include="@(LlmTckServiceContent)"
      Link="llm-tck-service\%(RecursiveDir)%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest"
      Visible="false" />
  </ItemGroup>
</Project>
